// Lista de elementos con información detallada
const elementos = [
    { simbolo: 'H', nombre: 'Hidrógeno', numero: 1, serie: 'No metales', masaAtomica: '1.008' },
    { simbolo: 'He', nombre: 'Helio', numero: 2, serie: 'Gases nobles', masaAtomica: '4.0026' },
    { simbolo: 'Li', nombre: 'Litio', numero: 3, serie: 'Metales alcalinos', masaAtomica: '6.94' },
    { simbolo: 'Be', nombre: 'Berilio', numero: 4, serie: 'Metales alcalinotérreos', masaAtomica: '9.0122' },
    { simbolo: 'B', nombre: 'Boro', numero: 5, serie: 'Metaloides', masaAtomica: '10.81' },
    { simbolo: 'C', nombre: 'Carbono', numero: 6, serie: 'No metales', masaAtomica: '12.011' },
    { simbolo: 'N', nombre: 'Nitrógeno', numero: 7, serie: 'No metales', masaAtomica: '14.007' },
    { simbolo: 'O', nombre: 'Oxígeno', numero: 8, serie: 'No metales', masaAtomica: '15.999' },
    { simbolo: 'F', nombre: 'Flúor', numero: 9, serie: 'Halógenos', masaAtomica: '18.998' },
    { simbolo: 'Ne', nombre: 'Neón', numero: 10, serie: 'Gases nobles', masaAtomica: '20.180' },
    { simbolo: 'Na', nombre: 'Sodio', numero: 11, serie: 'Metales alcalinos', masaAtomica: '22.990' },
    { simbolo: 'Mg', nombre: 'Magnesio', numero: 12, serie: 'Metales alcalinotérreos', masaAtomica: '24.305' },
    { simbolo: 'Al', nombre: 'Aluminio', numero: 13, serie: 'Metales', masaAtomica: '26.982' },
    { simbolo: 'Si', nombre: 'Silicio', numero: 14, serie: 'Metaloides', masaAtomica: '28.085' },
    { simbolo: 'P', nombre: 'Fósforo', numero: 15, serie: 'No metales', masaAtomica: '30.974' },
    { simbolo: 'S', nombre: 'Azufre', numero: 16, serie: 'No metales', masaAtomica: '32.06' },
    { simbolo: 'Cl', nombre: 'Cloro', numero: 17, serie: 'Halógenos', masaAtomica: '35.45' },
    { simbolo: 'Ar', nombre: 'Argón', numero: 18, serie: 'Gases nobles', masaAtomica: '39.948' },
    { simbolo: 'K', nombre: 'Potasio', numero: 19, serie: 'Metales alcalinos', masaAtomica: '39.098' },
    { simbolo: 'Ca', nombre: 'Calcio', numero: 20, serie: 'Metales alcalinotérreos', masaAtomica: '40.078' },
    { simbolo: 'Sc', nombre: 'Escandio', numero: 21, serie: 'Metales de transición', masaAtomica: '44.956' },
    { simbolo: 'Ti', nombre: 'Titanio', numero: 22, serie: 'Metales de transición', masaAtomica: '47.867' },
    { simbolo: 'V', nombre: 'Vanadio', numero: 23, serie: 'Metales de transición', masaAtomica: '50.941' },
    { simbolo: 'Cr', nombre: 'Cromo', numero: 24, serie: 'Metales de transición', masaAtomica: '51.996' },
    { simbolo: 'Mn', nombre: 'Manganeso', numero: 25, serie: 'Metales de transición', masaAtomica: '54.938' },
    { simbolo: 'Fe', nombre: 'Hierro', numero: 26, serie: 'Metales de transición', masaAtomica: '55.845' },
    { simbolo: 'Co', nombre: 'Cobalto', numero: 27, serie: 'Metales de transición', masaAtomica: '58.933' },
    { simbolo: 'Ni', nombre: 'Níquel', numero: 28, serie: 'Metales de transición', masaAtomica: '58.693' },
    { simbolo: 'Cu', nombre: 'Cobre', numero: 29, serie: 'Metales de transición', masaAtomica: '63.546' },
    { simbolo: 'Zn', nombre: 'Cinc', numero: 30, serie: 'Metales de transición', masaAtomica: '65.38' },
    { simbolo: 'Ga', nombre: 'Galio', numero: 31, serie: 'Metales', masaAtomica: '69.723' },
    { simbolo: 'Ge', nombre: 'Germanio', numero: 32, serie: 'Metaloides', masaAtomica: '72.630' },
    { simbolo: 'As', nombre: 'Arsénico', numero: 33, serie: 'Metaloides', masaAtomica: '74.922' },
    { simbolo: 'Se', nombre: 'Selenio', numero: 34, serie: 'No metales', masaAtomica: '78.971' },
    { simbolo: 'Br', nombre: 'Bromo', numero: 35, serie: 'Halógenos', masaAtomica: '79.904' },
    { simbolo: 'Kr', nombre: 'Kriptón', numero: 36, serie: 'Gases nobles', masaAtomica: '83.798' },
    { simbolo: 'Rb', nombre: 'Rubidio', numero: 37, serie: 'Metales alcalinos', masaAtomica: '85.468' },
    { simbolo: 'Sr', nombre: 'Estroncio', numero: 38, serie: 'Metales alcalinotérreos', masaAtomica: '87.62' },
    { simbolo: 'Y', nombre: 'Itrio', numero: 39, serie: 'Metales de transición', masaAtomica: '88.906' },
    { simbolo: 'Zr', nombre: 'Zirconio', numero: 40, serie: 'Metales de transición', masaAtomica: '91.224' },
    { simbolo: 'Nb', nombre: 'Niobio', numero: 41, serie: 'Metales de transición', masaAtomica: '92.906' },
    { simbolo: 'Mo', nombre: 'Molibdeno', numero: 42, serie: 'Metales de transición', masaAtomica: '95.95' },
    { simbolo: 'Tc', nombre: 'Tecnecio', numero: 43, serie: 'Metales de transición', masaAtomica: '98' },
    { simbolo: 'Ru', nombre: 'Rutenio', numero: 44, serie: 'Metales de transición', masaAtomica: '101.07' },
    { simbolo: 'Rh', nombre: 'Rodio', numero: 45, serie: 'Metales de transición', masaAtomica: '102.91' },
    { simbolo: 'Pd', nombre: 'Paladio', numero: 46, serie: 'Metales de transición', masaAtomica: '106.42' },
    { simbolo: 'Ag', nombre: 'Plata', numero: 47, serie: 'Metales de transición', masaAtomica: '107.87' },
    { simbolo: 'Cd', nombre: 'Cadmio', numero: 48, serie: 'Metales de transición', masaAtomica: '112.41' },
    { simbolo: 'In', nombre: 'Indio', numero: 49, serie: 'Metales', masaAtomica: '114.82' },
    { simbolo: 'Sn', nombre: 'Estaño', numero: 50, serie: 'Metales', masaAtomica: '118.71' },
    { simbolo: 'Sb', nombre: 'Antimonio', numero: 51, serie: 'Metaloides', masaAtomica: '121.76' },
    { simbolo: 'Te', nombre: 'Telurio', numero: 52, serie: 'Metaloides', masaAtomica: '127.60' },
    { simbolo: 'I', nombre: 'Yodo', numero: 53, serie: 'Halógenos', masaAtomica: '126.90' },
    { simbolo: 'Xe', nombre: 'Xenón', numero: 54, serie: 'Gases nobles', masaAtomica: '131.29' },
    { simbolo: 'Cs', nombre: 'Cesio', numero: 55, serie: 'Metales alcalinos', masaAtomica: '132.91' },
    { simbolo: 'Ba', nombre: 'Bario', numero: 56, serie: 'Metales alcalinotérreos', masaAtomica: '137.33' },
    { simbolo: 'La', nombre: 'Lantano', numero: 57, serie: 'Lantanidos', masaAtomica: '138.91' },
    { simbolo: 'Ce', nombre: 'Cerio', numero: 58, serie: 'Lantanidos', masaAtomica: '140.12' },
    { simbolo: 'Pr', nombre: 'Praseodimio', numero: 59, serie: 'Lantanidos', masaAtomica: '140.91' },
    { simbolo: 'Nd', nombre: 'Neodimio', numero: 60, serie: 'Lantanidos', masaAtomica: '144.24' },
    { simbolo: 'Pm', nombre: 'Prometio', numero: 61, serie: 'Lantanidos', masaAtomica: '145' },
    { simbolo: 'Sm', nombre: 'Samario', numero: 62, serie: 'Lantanidos', masaAtomica: '150.36' },
    { simbolo: 'Eu', nombre: 'Europio', numero: 63, serie: 'Lantanidos', masaAtomica: '151.96' },
    { simbolo: 'Gd', nombre: 'Gadolinio', numero: 64, serie: 'Lantanidos', masaAtomica: '157.25' },
    { simbolo: 'Tb', nombre: 'Terbio', numero: 65, serie: 'Lantanidos', masaAtomica: '158.93' },
    { simbolo: 'Dy', nombre: 'Disprosio', numero: 66, serie: 'Lantanidos', masaAtomica: '162.50' },
    { simbolo: 'Ho', nombre: 'Holmio', numero: 67, serie: 'Lantanidos', masaAtomica: '164.93' },
    { simbolo: 'Er', nombre: 'Erbio', numero: 68, serie: 'Lantanidos', masaAtomica: '167.26' },
    { simbolo: 'Tm', nombre: 'Tulio', numero: 69, serie: 'Lantanidos', masaAtomica: '168.93' },
    { simbolo: 'Yb', nombre: 'Iterbio', numero: 70, serie: 'Lantanidos', masaAtomica: '173.04' },
    { simbolo: 'Lu', nombre: 'Lutecio', numero: 71, serie: 'Lantanidos', masaAtomica: '174.97' },
    { simbolo: 'Hf', nombre: 'Hafnio', numero: 72, serie: 'Metales de transición', masaAtomica: '178.49' },
    { simbolo: 'Ta', nombre: 'Tantalio', numero: 73, serie: 'Metales de transición', masaAtomica: '180.95' },
    { simbolo: 'W', nombre: 'Wolframio', numero: 74, serie: 'Metales de transición', masaAtomica: '183.84' },
    { simbolo: 'Re', nombre: 'Renio', numero: 75, serie: 'Metales de transición', masaAtomica: '186.21' },
    { simbolo: 'Os', nombre: 'Osmio', numero: 76, serie: 'Metales de transición', masaAtomica: '190.23' },
    { simbolo: 'Ir', nombre: 'Iridio', numero: 77, serie: 'Metales de transición', masaAtomica: '192.22' },
    { simbolo: 'Pt', nombre: 'Platino', numero: 78, serie: 'Metales de transición', masaAtomica: '195.08' },
    { simbolo: 'Au', nombre: 'Oro', numero: 79, serie: 'Metales de transición', masaAtomica: '196.97' },
    { simbolo: 'Hg', nombre: 'Mercurio', numero: 80, serie: 'Metales de transición', masaAtomica: '200.59' },
    { simbolo: 'Tl', nombre: 'Talio', numero: 81, serie: 'Metales', masaAtomica: '204.38' },
    { simbolo: 'Pb', nombre: 'Plomo', numero: 82, serie: 'Metales', masaAtomica: '207.2' },
    { simbolo: 'Bi', nombre: 'Bismuto', numero: 83, serie: 'Metales', masaAtomica: '208.98' },
    { simbolo: 'Po', nombre: 'Polonio', numero: 84, serie: 'Metaloides', masaAtomica: '209' },
    { simbolo: 'At', nombre: 'Astato', numero: 85, serie: 'Halógenos', masaAtomica: '210' },
    { simbolo: 'Rn', nombre: 'Radón', numero: 86, serie: 'Gases nobles', masaAtomica: '222' },
    { simbolo: 'Fr', nombre: 'Francio', numero: 87, serie: 'Metales alcalinos', masaAtomica: '223' },
    { simbolo: 'Ra', nombre: 'Radón', numero: 88, serie: 'Metales alcalinotérreos', masaAtomica: '226' },
    { simbolo: 'Ac', nombre: 'Actinio', numero: 89, serie: 'Actínidos', masaAtomica: '227' },
    { simbolo: 'Th', nombre: 'Torio', numero: 90, serie: 'Actínidos', masaAtomica: '232.04' },
    { simbolo: 'Pa', nombre: 'Protactinio', numero: 91, serie: 'Actínidos', masaAtomica: '231.04' },
    { simbolo: 'U', nombre: 'Uranio', numero: 92, serie: 'Actínidos', masaAtomica: '238.03' },
    { simbolo: 'Np', nombre: 'Neptunio', numero: 93, serie: 'Actínidos', masaAtomica: '237' },
    { simbolo: 'Pu', nombre: 'Plutonio', numero: 94, serie: 'Actínidos', masaAtomica: '244' },
    { simbolo: 'Am', nombre: 'Americio', numero: 95, serie: 'Actínidos', masaAtomica: '243' },
    { simbolo: 'Cm', nombre: 'Curio', numero: 96, serie: 'Actínidos', masaAtomica: '247' },
    { simbolo: 'Bk', nombre: 'Berquelio', numero: 97, serie: 'Actínidos', masaAtomica: '247' },
    { simbolo: 'Cf', nombre: 'Californio', numero: 98, serie: 'Actínidos', masaAtomica: '251' },
    { simbolo: 'Es', nombre: 'Einstenio', numero: 99, serie: 'Actínidos', masaAtomica: '252' },
    { simbolo: 'Fm', nombre: 'Fermio', numero: 100, serie: 'Actínidos', masaAtomica: '257' },
    { simbolo: 'Md', nombre: 'Mendelevio', numero: 101, serie: 'Actínidos', masaAtomica: '258' },
    { simbolo: 'No', nombre: 'Nobelio', numero: 102, serie: 'Actínidos', masaAtomica: '259' },
    { simbolo: 'Lr', nombre: 'Lawrencio', numero: 103, serie: 'Actínidos', masaAtomica: '262' },
    { simbolo: 'Rf', nombre: 'Rutherfordio', numero: 104, serie: 'Elementos transactínidos', masaAtomica: '267' },
    { simbolo: 'Db', nombre: 'Dubnio', numero: 105, serie: 'Elementos transactínidos', masaAtomica: '268' },
    { simbolo: 'Sg', nombre: 'Seaborgio', numero: 106, serie: 'Elementos transactínidos', masaAtomica: '271' },
    { simbolo: 'Bh', nombre: 'Bohrio', numero: 107, serie: 'Elementos transactínidos', masaAtomica: '270' },
    { simbolo: 'Hs', nombre: 'Hassio', numero: 108, serie: 'Elementos transactínidos', masaAtomica: '277' },
    { simbolo: 'Mt', nombre: 'Meitnerio', numero: 109, serie: 'Elementos transactínidos', masaAtomica: '278' },
    { simbolo: 'Ds', nombre: 'Darmstadtio', numero: 110, serie: 'Elementos transactínidos', masaAtomica: '281' },
    { simbolo: 'Rg', nombre: 'Roentgenio', numero: 111, serie: 'Elementos transactínidos', masaAtomica: '282' },
    { simbolo: 'Cn', nombre: 'Copernicio', numero: 112, serie: 'Elementos transactínidos', masaAtomica: '285' },
    { simbolo: 'Nh', nombre: 'Nihonio', numero: 113, serie: 'Elementos transactínidos', masaAtomica: '286' },
    { simbolo: 'Fl', nombre: 'Flerovio', numero: 114, serie: 'Elementos transactínidos', masaAtomica: '289' },
    { simbolo: 'Mc', nombre: 'Moscovio', numero: 115, serie: 'Elementos transactínidos', masaAtomica: '288' },
    { simbolo: 'Lv', nombre: 'Livermorio', numero: 116, serie: 'Elementos transactínidos', masaAtomica: '293' },
    { simbolo: 'Ts', nombre: 'Tenesino', numero: 117, serie: 'Elementos transactínidos', masaAtomica: '294' },
    { simbolo: 'Og', nombre: 'Oganesón', numero: 118, serie: 'Elementos transactínidos', masaAtomica: '294' }
  ];


  function openModal(simbolo) {
    // Buscar el elemento en la lista según su símbolo
    const elemento = elementos.find(el => el.simbolo === simbolo);

    if (elemento) {
      // Actualizar el contenido del modal con la información del elemento
      const contenido = `
        <strong>Nombre:</strong> ${elemento.nombre}<br>
        <strong>Símbolo:</strong> ${elemento.simbolo}<br>
        <strong>Número atómico:</strong> ${elemento.numero}<br>
        <strong>Serie química:</strong> ${elemento.serie}<br>
        <strong>Masa atómica:</strong> ${elemento.masaAtomica}
      `;
      document.getElementById('modalContent').innerHTML = contenido;
      document.getElementById('modalOverlay').classList.add('active');
    }
  }

  function closeModal() {
    document.getElementById('modalOverlay').classList.remove('active');
  }